Update patch set 2
Patch Set 2:

I just tried it, and when I go to the Yin view, I get the following:
-------------------
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.opendaylight.yangtools.yang.parser.repo.YangTextSchemaContextResolver.<clinit>(YangTextSchemaContextResolver.java:51)
	at com.cisco.yangide.ext.model.editor.YinBuilder.build(YinBuilder.java:53)
	at com.cisco.yangide.ext.model.editor.YangMultiPageEditorPart$LoadYinViewJob.run(YangMultiPageEditorPart.java:375)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory cannot be found by com.cisco.yangide.core_1.1.1.201604290236
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
-------------------

I'll look at this more tomorrow, unless you have an immediate idea.

Patch-set: 2